set_property IOSTANDARD LVCMOS33 [get_ports {dir_btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dir_btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dir_btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dir_btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_led[0]}]
set_property PACKAGE_PIN T18 [get_ports {dir_btn[3]}]
set_property PACKAGE_PIN U17 [get_ports {dir_btn[2]}]
set_property PACKAGE_PIN W19 [get_ports {dir_btn[1]}]
set_property PACKAGE_PIN T17 [get_ports {dir_btn[0]}]
set_property PACKAGE_PIN L1 [get_ports {send_led[7]}]
set_property PACKAGE_PIN P1 [get_ports {send_led[6]}]
set_property PACKAGE_PIN N3 [get_ports {send_led[5]}]
set_property PACKAGE_PIN P3 [get_ports {send_led[4]}]
set_property PACKAGE_PIN U3 [get_ports {send_led[3]}]
set_property PACKAGE_PIN W3 [get_ports {send_led[2]}]
set_property PACKAGE_PIN V3 [get_ports {send_led[1]}]
set_property PACKAGE_PIN V13 [get_ports {send_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports data]
set_property IOSTANDARD LVCMOS33 [get_ports ready]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports speed_up]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports test_sw]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN L17 [get_ports data]
set_property PACKAGE_PIN U16 [get_ports ready]
set_property PACKAGE_PIN V17 [get_ports rst]
set_property PACKAGE_PIN W16 [get_ports speed_up]
set_property PACKAGE_PIN U18 [get_ports start]
set_property PACKAGE_PIN V16 [get_ports test_sw]


set_property IOSTANDARD LVCMOS33 [get_ports test_data]
set_property PACKAGE_PIN J1 [get_ports test_data]



set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property PACKAGE_PIN V16 [get_ports en]

set_property IOSTANDARD LVCMOS33 [get_ports {turn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {turn[0]}]
set_property PACKAGE_PIN R2 [get_ports {turn[1]}]
set_property PACKAGE_PIN T1 [get_ports {turn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports shoot]
set_property PACKAGE_PIN U18 [get_ports shoot]

set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property PACKAGE_PIN V7 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports vauxn6]
set_property IOSTANDARD LVCMOS33 [get_ports vauxn7]
set_property IOSTANDARD LVCMOS33 [get_ports vauxn14]
set_property IOSTANDARD LVCMOS33 [get_ports vauxn15]
set_property IOSTANDARD LVCMOS33 [get_ports vauxp6]
set_property IOSTANDARD LVCMOS33 [get_ports vauxp7]
set_property IOSTANDARD LVCMOS33 [get_ports vauxp14]
set_property IOSTANDARD LVCMOS33 [get_ports vauxp15]
set_property PACKAGE_PIN K3 [get_ports vauxn6]
set_property PACKAGE_PIN M1 [get_ports vauxn7]
set_property PACKAGE_PIN M3 [get_ports vauxn14]
set_property PACKAGE_PIN N1 [get_ports vauxn15]
set_property PACKAGE_PIN J3 [get_ports vauxp6]
set_property PACKAGE_PIN M2 [get_ports vauxp7]
set_property PACKAGE_PIN L3 [get_ports vauxp14]
set_property PACKAGE_PIN N2 [get_ports vauxp15]

set_property IOSTANDARD LVCMOS33 [get_ports {state_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state_led[0]}]
set_property PACKAGE_PIN V19 [get_ports {state_led[3]}]
set_property PACKAGE_PIN U19 [get_ports {state_led[2]}]
set_property PACKAGE_PIN E19 [get_ports {state_led[1]}]
set_property PACKAGE_PIN U16 [get_ports {state_led[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports dir_input]
set_property PACKAGE_PIN W17 [get_ports dir_input]
